:: updates

diff --git a/feedfaetcher b/feedfaetcher
--- a/feedfaetcher
+++ b/feedfaetcher
@@ -2,103 +2,91 @@
 #
 # Simple feed downloader based on urldiff.
 
-feedcacherdir=${XDG_VAR_HOME}/lib/feedfaetcher
+feedcacherdir=${XDG_VAR_HOME:?}/lib/feedfaetcher;
 
-urllist=${feedcacherdir}/urls.txt
+urllist=${feedcacherdir}/urls.txt;
 typeset -x \
-        cachedir=${feedcacherdir}/cache \
-        reportnew=${feedcacherdir}/report.txt \
-        table=${feedcacherdir}/table.txt;
+    cachedir=${feedcacherdir}/cache \
+    reportnew=${feedcacherdir}/report.txt \
+    table=${feedcacherdir}/table.txt;
 
-__feedcacher_do()
-{
-        typeset \
-                filename \
-                onlinexml \
-                url=${1,,};
+function __feedcacher_do {
+    typeset \
+        filename \
+        onlinexml \
+        url=${1,,};
 
-        [[ $url == \#* ]] && return 1;
+    [[ $url == \#* ]] && return 1;
 
+    if
+        [[ $url =~ ^https?://.*\.[a-z]*/.*$ ]];
+    then
+        filename=${url:0:121};
+        filename=${filename//_/-};
+        filename=${filename// /_};
+        filename=${filename//\//_};
+        onlinexml=${cachedir}/${filename}.xml;
+        wget --no-verbose \
+            --connect-timeout=3 \
+            --content-on-error \
+            --dns-timeout=3 \
+            --ignore-length \
+            --inet4-only \
+            --no-cache \
+            --no-cookies \
+            --no-http-keep-alive \
+            --read-timeout=3 \
+            --tries=1 \
+            -O "$onlinexml" \
+            "$1";
         if
-                [[ $url =~ ^https?://.*\.[a-z]*/.*$ ]]
+            [[ $(stat -c %s "$onlinexml" 2>/dev/null) -ge 2 ]];
         then
-                filename=${url:0:121}
-                filename=${filename//_/-}
-                filename=${filename// /_}
-                filename=${filename//\//_}
-                onlinexml=${cachedir}/${filename}.xml
-                wget --no-verbose \
-                        --connect-timeout=3 \
-                        --content-on-error \
-                        --dns-timeout=3 \
-                        --ignore-length \
-                        --inet4-only \
-                        --no-cache \
-                        --no-cookies \
-                        --no-http-keep-alive \
-                        --read-timeout=3 \
-                        --tries=1 \
-                        -O "$onlinexml" \
-                        "$1";
-                if
-                        [[ $(stat -c %s "$onlinexml" 2>/dev/null) -ge 2 ]]
-                then
-                        printf '%s %s\n' "$1" "${onlinexml##*/}" \
-                        >> "$table";
-                        printf 'SUCCESS %(%Y-%m-%d_%H:%M)T URL:%s synchronized\n' -1 "$1" \
-                        1>&3;
-                else
-                        rm -- "$onlinexml"
-                        printf 'FAIL %(%Y-%m-%d_%H:%M)T URL:%s unattainable\n' -1 "$1" \
-                        1>&3;
-                        return 1
-                fi
-        else
-                printf 'FAIL %(%Y-%m-%d_%H:%M)T URL:%s does not match\n' -1 "$1" \
+            printf '%s %s\n' "$1" "${onlinexml##*/}" >> "$table";
+            printf 'SUCCESS %(%Y-%m-%d_%H:%M)T URL:%s synchronized\n' -1 "$1" \
                 1>&3;
-                return 1
-        fi
-}
+        else
+            rm -- "$onlinexml";
+            printf 'FAIL %(%Y-%m-%d_%H:%M)T URL:%s unattainable\n' -1 "$1" 1>&3;
+            return 1;
+        fi;
+    else
+        printf 'FAIL %(%Y-%m-%d_%H:%M)T URL:%s does not match\n' -1 "$1" 1>&3;
+        return 1;
+    fi;
+};
 
-if
-        [[ -n $1 ]]
-then
-        if
-                <<< "$1" \
-                cat "$urllist" -  \
-                | sort -u \
-                > "$urllist.$$";
-        then
-                mv "$urllist.$$" "$urllist";
-        fi
-        exit $?
-fi
+[[ -n $1 ]] && {
+    <<< "$1" cat "$urllist" - |
+    sort -u > "$urllist.$$" &&
+        mv "$urllist.$$" "$urllist";
 
-export -f __feedcacher_do
+    exit $?;
+};
+
+export -f __feedcacher_do;
 
 [[ -d $cachedir ]] || mkdir -p -- "$cachedir";
 [[ -f $reportnew ]] && rm -- "$reportnew";
 [[ -f $table ]] && rm -- "$table";
-if
-        [[ -d $cachedir ]]
-then
-        rm -r -- "$cachedir"
-        mkdir -p -- "$cachedir"
-fi
+[[ -d $cachedir ]] && {
+    rm -r -- "$cachedir";
+    mkdir -p -- "$cachedir";
+};
 
-tput bold setaf 7 ; printf '\n%s\n' "CHECK" ; tput sgr0
+tput bold setaf 7; printf '\n%s\n' "CHECK"; tput sgr0;
 exec 3>>"$reportnew";
-xargs -I {} -a "$urllist" -n 1 -P 4 -i bash -c '__feedcacher_do "$@"' _ {}
+xargs -I {} -a "$urllist" -n 1 -P 4 -i bash -c '__feedcacher_do "$@";' _ {};
 exec 3<&-;
 
 if
-        [[ $(stat -c %s "$reportnew" 2>/dev/null) -ge 2 ]]
+    [[ $(stat -c %s "$reportnew" 2>/dev/null;) -ge 2 ]];
 then
-        tput bold setaf 7 ; printf '\n%s\n' "REPORT" ; tput sgr0
-        cat "$reportnew"
+    tput bold setaf 7; printf '\n%s\n' "REPORT"; tput sgr0;
+    cat "$reportnew";
 else
-        printf '%(%Y-%m-%d_%H:%M)T %s\n' -1 "ERROR Report has not been created" \
-        1>&2;
-fi
+    printf '%(%Y-%m-%d_%H:%M)T %s\n' -1 "ERROR Report has not been created" 1>&2;
+    exit 1;
+fi;
 
-# vim: set ts=8 sw=8 tw=0 et :
+# vim: set ts=4 sw=4 tw=0 et :
diff --git a/mail-send b/mail-send
--- a/mail-send
+++ b/mail-send
@@ -2,46 +2,41 @@
 #
 # Send mail via msmtp-queue and give notification + sound.
 
-if
-         exec 9<"$0";
-         ! flock -n 9
-then
-         printf '%s\n' "sorry, I am already running" 1>&2;
-         exit 1
-fi
+exec 9<"$0";
+flock -n 9 || {
+    printf '%s\n' "sorry, I am already running" 1>&2;
+    exit 1;
+};
 
-maildir=${XDG_VAR_HOME}/mail/queue
-if
-        ! [[ -d $maildir ]]
-then
-        printf "maildir '%s' is not a directory\n" "$maildir" 1>&2;
-        exit 1
-fi
+maildir=${XDG_VAR_HOME:?}/mail/queue;
+[[ -d $maildir ]] || {
+    printf "maildir '%s' is not a directory\n" "$maildir" 1>&2;
+    exit 1;
+};
 
-shopt -s nullglob
-shopt -s extglob
-shopt -s dotglob
-set -- "${maildir}/"!(\.*)
+shopt -s nullglob;
+shopt -s extglob;
+shopt -s dotglob;
+set -- "${maildir}/"!(\.*);
 
 (($#)) && cnt=$# || exit 1;
 
-i=0
+i=0;
 until
-        (( ! $# ))
+    ! (($#));
 do
-        case $i in
-        30)
-                loggi 3 .email.error "Delivery error. [posteo] Mails not sent: ${cnt}"
-                exit 1
-        ;;
-        *)
-                msmtp-queue -r
-                set -- "${maildir}/"!(\.*)
-                ((i++))
-                sleep 1
-        esac
-done
+    case $i in
+        (30)
+            loggi 3 .email.error "Delivery error. [posteo] Mails not sent: ${cnt}";
+            exit 1;;
+        (*)
+            msmtp-queue -r;
+            set -- "${maildir}/"!(\.*);
+            ((i++));
+            sleep 1;
+    esac;
+done;
 
-loggi 6 .email.bounced "[posteo] Sent Mails: ${cnt}"
+loggi 6 .email.bounced "[posteo] Sent Mails: ${cnt}";
 
-# vim: set ts=8 sw=8 tw=0 et :
+# vim: set ts=4 sw=4 tw=0 et :
diff --git a/pass-copy b/pass-copy
--- a/pass-copy
+++ b/pass-copy
@@ -2,41 +2,40 @@
 #
 # Copy password from pass.
 
-__select ()
-{
-        read -r file < <(
-                find "${HOME}/.password-store/" \
-                        -type f -name "*.gpg" -printf '%f\n' \
-                | sed 's/.gpg$//g' \
-                | sort \
-                | menu "$1" "> ";
-        )
-}
+function __select {
+    read -r file < <(
+        find "${HOME}/.password-store/" \
+            -type f -name "*.gpg" -printf '%f\n' |
+        sed 's/.gpg$//g' |
+        sort |
+        menu "$1" "> ";
+    );
+};
 
 if
-        test-tty 2>/dev/null;
+    test-tty 2>/dev/null;
 then
-        menu=fzf
+    menu=fzf;
 else
-        menu=dmenu2
-fi
+    menu=dmenu2;
+fi;
 
-__select "$menu"
+'__select' "$menu";
 
 if
-        [[ -f ${HOME}/.password-store/${file}.gpg ]]
+    [[ -f ${HOME}/.password-store/${file}.gpg ]];
 then
-        if
-                [[ $1 == --type ]]
-        then
-                pass show "$file" \
-                | xdotool type --clearmodifiers --file -;
-        else
-                PASSWORD_STORE_CLIP_TIME=10 pass show -c "$file"
-        fi
+    if
+        [[ $1 == --type ]];
+    then
+        pass show "$file" |
+        xdotool type --clearmodifiers --file -;
+    else
+        PASSWORD_STORE_CLIP_TIME=10 pass show -c "$file";
+    fi;
 else
-        printf '%s:Error: Nothing has been chosen\n' "$0" 1>&2;
-        exit 1
-fi
+    printf '%s:Error: Nothing has been chosen\n' "$0" 1>&2;
+    exit 1;
+fi;
 
-# vim: set ts=8 sw=8 tw=0 et :
+# vim: set ts=4 sw=4 tw=0 et :
diff --git a/run b/run
--- a/run
+++ b/run
@@ -6,104 +6,87 @@
 # -k keep/wait
 # -n open cmd in new terminal-emulator
 
-OPTIND=1
-OPTERR=1
-opt=
+OPTIND=1 \
+OPTERR=1 \
+opt=;
 
 typeset -i \
-        flag_f= \
-        flag_k= \
-        flag_n=;
+    flag_f= \
+    flag_k= \
+    flag_n=;
 
 typeset -a \
-        command \
-        command_quoted;
+    command \
+    command_quoted;
 
 while
-        getopts :fkn opt
+    getopts :fkn opt;
 do
-        case $opt in
-        f)
-                flag_f=1
-        ;;
-        k)
-                flag_k=1
-        ;;
-        n)
-                flag_n=1
-        ;;
-        \?)
-                printf "Unknown flag: '-%s'\n" "$OPTARG" 1>&2;
-                exit 1
-        esac
-done
-shift $(( OPTIND - 1 ))
+    case $opt in
+        (f)
+            flag_f=1;;
+        (k)
+            flag_k=1;;
+        (n)
+            flag_n=1;;
+        (\?)
+            printf "Unknown flag: '-%s'\n" "$OPTARG" 1>&2;
+            exit 1;
+    esac;
+done;
+shift $((OPTIND - 1));
 
 typeset \
-        a \
-        q;
+    a \
+    q;
 
-for a
-do
-        printf -v q '%q' "$a"
-        command_quoted+=( "$q" )
-        command+=( "$a" )
-done
-
+for a; do
+    printf -v q '%q' "$a";
+    command_quoted+=("$q");
+    command+=("$a");
+done;
 
 command -v "${command[0]}" 1>/dev/null 2>&1 || {
-        printf "error: command not found: '%s'\n" "${command[0]}" 1>&2;
-        exit 1
-}
+    printf "error: command not found: '%s'\n" "${command[0]}" 1>&2;
+    exit 1;
+};
 
 if
-        test-tty 2>/dev/null;
+    test-tty 2>/dev/null;
 then
-        case ${flag_f}${flag_n}${flag_k} in
-        111)
-                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}"
-        ;;
-        110)
-                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}"
-        ;;
-        100)
-                setsidw "${command[0]}" "${command[@]}"
-        ;;
-        011)
-                x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}"
-        ;;
-        010)
-                x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}"
-        ;;
-        001)
-                exec ${SHELL:-sh} -c "${command[0]} ${command_quoted[@]:1};builtin printf '%s\n' 'Press ENTER to continue';builtin read"
-        ;;
-        000)
-                exec -a "${command[0]}" "${command[@]}"
-        esac
+    case ${flag_f}${flag_n}${flag_k} in
+    (111)
+        daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}";;
+    (110)
+        daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}";;
+    (100)
+        setsidw "${command[0]}" "${command[@]}";;
+    (011)
+        x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}";;
+    (010)
+        x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}";;
+    (001)
+        exec ${SHELL:-sh} -c "${command[0]} ${command_quoted[@]:1};builtin printf '%s\n' 'Press ENTER to continue';builtin read";;
+    (000)
+        exec -a "${command[0]}" "${command[@]}";
+    esac;
 else
-        case ${flag_f}${flag_n}${flag_k} in
-        111)
-                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}"
-        ;;
-        110)
-                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}"
-        ;;
-        100)
-                setsidw "${command[0]}" "${command[@]}"
-        ;;
-        011)
-                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}"
-        ;;
-        010)
-                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}"
-        ;;
-        001)
-                daemonize ${SHELL:-sh} -c "${command[0]} ${command_quoted[@]:1};builtin printf '%s\n' 'Press ENTER to continue';builtin read"
-        ;;
-        000)
-                setsidw "${command[0]}" "${command[@]}"
-        esac
-fi
+    case ${flag_f}${flag_n}${flag_k} in
+    (111)
+        daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}";;
+    (110)
+        daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}";;
+    (100)
+        setsidw "${command[0]}" "${command[@]}";;
+    (011)
+        daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}";;
+    (010)
+        daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}";;
+    (001)
+        daemonize ${SHELL:-sh} -c "${command[0]} ${command_quoted[@]:1};builtin printf '%s\n' 'Press ENTER to continue';builtin read";;
+    (000)
+        setsidw "${command[0]}" "${command[@]}";
+    esac;
+fi;
 
-# vim: set ts=8 sw=8 tw=0 et :
+# vim: set ts=4 sw=4 tw=0 et :
diff --git a/task-local b/task-local
--- a/task-local
+++ b/task-local
@@ -2,29 +2,27 @@
 #
 # Simple wrapper for using taskwarrior with local "task-repos".
 
-TASKRC="${TASKRC:-${PWD}/.task/taskrc}"
-
-export TASKRC
+TASKRC="${TASKRC:-${PWD}/.task/taskrc}";
+export TASKRC;
 
 case "$1" in
-init)
+    (init)
         if
-                test -d "${PWD}/.task"
+            test -d "${PWD}/.task";
         then
-                printf '%s:Error:82: Could not create a task repository: "%s/.task/" is existing\n' "$0" "$PWD" \
-                1>&2;
-                exit 82
+            printf '%s:Error:82: Could not create a task repository: "%s/.task/" is existing\n' "$0" "$PWD" \
+                    1>&2;
+            exit 82;
         else
-                mkdir -p -- "${PWD}/.task/data" && task config data.location "${PWD}/.task/data";
-        fi
-;;
---)
-        shift 1
-        task "$@"
-;;
-*)
+            mkdir -p -- "${PWD}/.task/data" &&
+                task config data.location "${PWD}/.task/data";
+        fi;;
+    (--)
+        shift 1;
+        task "$@";;
+    (*)
         printf '%s:Error:83: Unknown parameter: %s\n' "$0" "$1" 1>&2;
-        exit 83
-esac
+        exit 83;
+esac;
 
-# vim: set ts=8 sw=8 tw=0 et :
+# vim: set ts=4 sw=4 tw=0 et :
diff --git a/test-tty b/test-tty
--- a/test-tty
+++ b/test-tty
@@ -2,16 +2,14 @@
 #
 # Test if tty is available.
 
-if
-        [[ ! $BASH_SOURCE == $0 ]]
-then
-        printf '%s\n' "Error: Do not execute me via source" 1>&2;
-        return 1 2>/dev/null;
-fi
+[[ $BASH_SOURCE == $0 ]] || {
+    printf '%s\n' "Error: Do not execute me via source" 1>&2;
+    return 1 2>/dev/null;
+};
 
-tty=$(ps -p "$PPID" -o tty=)
-tty=${tty/\?/}
+tty=$(ps -p "$PPID" -o tty=);
+tty=${tty/\?/};
 
 [[ -n $tty ]] && printf '/dev/%s\n' "$tty" 1>&2;
 
-# vim: set ts=8 sw=8 tw=0 et :
+# vim: set ts=4 sw=4 tw=0 et :
