update

diff --git a/feedfaetcher b/feedfaetcher
--- a/feedfaetcher
+++ b/feedfaetcher
@@ -44,8 +44,8 @@ function __feedcacher_do {
             [[ $(stat -c %s -- "$onlinexml" 2>/dev/null) -ge 2 ]];
         then
             printf '%s %s\n' "$1" "${onlinexml##*/}" >> "$table";
-            printf 'SUCCESS %(%Y-%m-%d_%H:%M)T URL:%s synchronized\n' -1 "$1" \
-                1>&3;
+            # printf 'SUCCESS %(%Y-%m-%d_%H:%M)T URL:%s synchronized\n' -1 "$1" \
+                # 1>&3;
         else
             rm -- "$onlinexml";
             printf 'FAIL %(%Y-%m-%d_%H:%M)T URL:%s unavailable\n' -1 "$1" 1>&3;
@@ -78,19 +78,19 @@ export -f __feedcacher_do;
     mkdir -p -- "$cachedir";
 };
 
-tput bold setaf 7; printf '\n%s\n' CHECK; tput sgr0;
+tput bold setaf 7; printf '\n%s\n' GET; tput sgr0;
 exec 3>>"$reportnew";
 xargs -I {} -a "$urllist" -n 1 -P 4 -i bash -c '__feedcacher_do "$@";' _ {};
 exec 3<&-;
 
-if
-    [[ $(stat -c %s -- "$reportnew" 2>/dev/null) -ge 2 ]];
-then
+# if
+#     [[ $(stat -c %s -- "$reportnew" 2>/dev/null) -ge 2 ]];
+# then
     tput bold setaf 7; printf '\n%s\n' REPORT; tput sgr0;
     cat -- "$reportnew";
-else
-    printf '%(%Y-%m-%d_%H:%M)T %s\n' -1 'ERROR Report has not been created' 1>&2;
-    exit 1;
-fi;
+# else
+#     printf '%(%Y-%m-%d_%H:%M)T \n%s\n' -1 'ERROR Report has not been created' 1>&2;
+#     exit 1;
+# fi;
 
 # vim: set ft=sh :
