:: updates

diff --git a/get-news b/get-news
--- a/get-news
+++ b/get-news
@@ -2,10 +2,25 @@
 #
 # Wrapper for getting my news.
 
-feedfaetcher
+if
+        test-inet
+then
+        feedfaetcher &
+        urldiff -nv &
+else
+        printf 'network.error: %s\n' "We are offline. News have not been updated" 1>&2;
+        if
+                test -n "$DISPLAY"
+        then
+                notify-send --category=network.error \
+                        "network.error: We are offline" \
+                        "News have not been updated";
+        else
+                sound _ "network.error:"
+        fi
+        exit 1
+fi
 
-newsbeuter -r -l 3 -d "${XDG_VAR_HOME}/log/newsbeuter.log"
-
-urldiff -nv
+wait
 
 # vim: set ts=8 sw=8 tw=0 et :
diff --git a/mail-send b/mail-send
--- a/mail-send
+++ b/mail-send
@@ -32,6 +32,7 @@ do
         case $i in
         30)
                 printf -v msg '[posteo] Mails not sent: %d\n' "$cnt"
+                printf 'email.error:\n%s\n' "$msg" 1>&2;
                 if
                         [[ -n $DISPLAY ]]
                 then
@@ -39,7 +40,6 @@ do
                                 "email.error: Mail fetch error" "$msg";
                 else
                         sound _ "email.error:"
-                        printf 'Mail fetch error:\n%s\n' "$msg" 1>&2;
                 fi
                 exit 1
         ;;
@@ -52,13 +52,13 @@ do
 done
 
 msg="[posteo] Sent Mails: ${cnt}"
+printf 'email.bounced:\n%s\n' "$msg" 1>&2;
 if
         [[ -n $DISPLAY ]]
 then
         notify-send --category=email.bounced -u normal "email.bounced:" "$msg"
 else
         sound _ "email.bounced:"
-        printf 'Mail bounced:\n%s\n' "$msg" 1>&2;
 fi
 
 # vim: set ts=8 sw=8 tw=0 et :
diff --git a/mail-update b/mail-update
--- a/mail-update
+++ b/mail-update
@@ -2,17 +2,27 @@
 #
 # Update mail dirs.
 
-test-inet || {
-        printf 'error: %s\n' "We are offline Mails have not been updated" 1>&2;
-        notify-send --category=network.error \
-                "network.error: You are offline" \
-                "Mails have not been updated";
+if
+        test-inet
+then
+        mail-send &
+        #mail-hook-pre
+        mail-get
+        #mail-hook-post
+else
+        printf 'network.error: %s\n' "We are offline. Mails have not been updated" 1>&2;
+        if
+                test -n "$DISPLAY"
+        then
+                notify-send --category=network.error \
+                        "network.error: We are offline" \
+                        "Mails have not been updated";
+        else
+                sound _ "network.error:"
+        fi
         exit 1
-}
+fi
 
-mail-send
-mail-hook-pre
-mail-get
-mail-hook-post
+wait
 
 # vim: set ts=8 sw=8 tw=0 et :
