update

diff --git a/mail-send b/mail-send
--- a/mail-send
+++ b/mail-send
@@ -4,14 +4,14 @@
 
 exec 9<"$0";
 flock -n 9 || {
-    printf 'sorry, I am already running\n' 1>&2;
-    exit 1;
+	printf 'sorry, I am already running\n' 1>&2;
+	exit 1;
 };
 
 maildir=${XDG_VAR_HOME:?}/mail/queue;
 [[ -d $maildir ]] || {
-    printf "maildir '%s' is not a directory\n" "$maildir" 1>&2;
-    exit 1;
+	printf "maildir '%s' is not a directory\n" "$maildir" 1>&2;
+	exit 1;
 };
 
 shopt -s nullglob;
@@ -20,23 +20,23 @@ shopt -s dotglob;
 set -- "$maildir/"!(\.*);
 
 (($#)) &&
-    cnt=$# ||
-        exit 1;
+	cnt=$# ||
+		exit 1;
 
 i=0;
 until
-    ! (($#));
+	! (($#));
 do
-    case $i in
-        (30)
-            run-logger 3 .email.error "Delivery error. [posteo] Mails not sent: $cnt";
-            exit 1;;
-        (*)
-            msmtpqw -r;
-            set -- "$maildir/"!(\.*);
-            ((i++));
-            sleep 1;
-    esac;
+	case $i in
+		(30)
+			run-logger 3 .email.error "Delivery error. [posteo] Mails not sent: $cnt";
+			exit 1;;
+		(*)
+			msmtpqw -r;
+			set -- "$maildir/"!(\.*);
+			((i++));
+			sleep 1;
+	esac;
 done;
 
 run-logger 6 .email.bounced "[posteo] Sent Mails: $cnt";
diff --git a/open b/open
--- a/open
+++ b/open
@@ -12,50 +12,50 @@ mime= \
 opt=;
 
 while
-    getopts :A:f: opt;
+	getopts :A:f: opt;
 do
-    case $opt in
-        (A)
-            case $OPTARG in
-                (view|vview|edit|vedit|compose|vcompose|dog|cdog|about|gview|gedit|gcompose)
-                    flag_A=${flag_A:+$flag_A }$OPTARG;;
-                (*)
-                    printf 'Unknown action: %s\n' "$OPTARG" 1>&2;
-                    exit 1;;
-            esac;;
-        (f)
-            readonly flag_f=$OPTARG;;
-        (\?)
-            printf 'Unknown flag: -%s\n' "$OPTARG" 1>&2;
-            exit 1;;
-    esac;
+	case $opt in
+		(A)
+			case $OPTARG in
+				(view|vview|edit|vedit|compose|vcompose|dog|cdog|about|gview|gedit|gcompose)
+					flag_A=${flag_A:+$flag_A }$OPTARG;;
+				(*)
+					printf 'Unknown action: %s\n' "$OPTARG" 1>&2;
+					exit 1;;
+			esac;;
+		(f)
+			readonly flag_f=$OPTARG;;
+		(\?)
+			printf 'Unknown flag: -%s\n' "$OPTARG" 1>&2;
+			exit 1;;
+	esac;
 done;
 
 test -n "$flag_f" || {
-    printf 'File operand is missing\n' 1>&2;
-    exit 1;
+	printf 'File operand is missing\n' 1>&2;
+	exit 1;
 };
 
 eval "$(mime_database detect "$flag_f")";
 
 if
-    test "$m" != ?;
+	test "$m" != ?;
 then
-    mime=$m;
+	mime=$m;
 elif
-    test "$g" != ?;
+	test "$g" != ?;
 then
-    mime=$g;
+	mime=$g;
 else
-    mime=$(file -L -b --mime-type "$flag_f");
+	mime=$(file -L -b --mime-type "$flag_f");
 fi;
 
 . "$XDG_CONFIG_HOME/"mailcap.d/$mime;
 
 for A in $flag_A; do
-    "$A" "$flag_f" &&
-        break;
-    printf 'action for mime <%s> was <%s>\n' "$mime" "$A" 1>&2;
+	"$A" "$flag_f" &&
+		break;
+	printf 'action for mime <%s> was <%s>\n' "$mime" "$A" 1>&2;
 done;
 
 # vim: set ft=sh :
diff --git a/pass2clipboard b/pass2clipboard
--- a/pass2clipboard
+++ b/pass2clipboard
@@ -3,39 +3,39 @@
 # Copy password from pass.
 
 function __select {
-    read -r file < <(
-        find "$HOME/".password-store/ \
-            -type f -name \*.gpg -printf %f\\n |
-        sed 's/.gpg$//g' |
-        sort |
-        menu "$1";
-    );
+	read -r file < <(
+		find "$HOME/".password-store/ \
+			-type f -name \*.gpg -printf %f\\n |
+		sed 's/.gpg$//g' |
+		sort |
+		menu "$1";
+	);
 };
 
 if
-    test-ctty;
+	test-ctty;
 then
-    menu=fzf;
+	menu=fzf;
 else
-    menu=dmenu2;
+	menu=dmenu2;
 fi;
 
 __select "$menu";
 
 if
-    [[ -f $HOME/.password-store/$file.gpg ]];
+	[[ -f $HOME/.password-store/$file.gpg ]];
 then
-    if
-        [[ $1 == --type ]];
-    then
-        pass show "$file" |
-        xdotool type --clearmodifiers --file -;
-    else
-        PASSWORD_STORE_CLIP_TIME=10 pass show -c "$file";
-    fi;
+	if
+		[[ $1 == --type ]];
+	then
+		pass show "$file" |
+		xdotool type --clearmodifiers --file -;
+	else
+		PASSWORD_STORE_CLIP_TIME=10 pass show -c "$file";
+	fi;
 else
-    printf '%s:Error: Nothing has been chosen\n' "$BASH_SOURCE" 1>&2;
-    exit 1;
+	printf '%s:Error: Nothing has been chosen\n' "$BASH_SOURCE" 1>&2;
+	exit 1;
 fi;
 
 # vim: set ft=sh :
