update

diff --git a/ARCHIVE/task-dir b/ARCHIVE/task-dir
--- a/ARCHIVE/task-dir
+++ b/ARCHIVE/task-dir
@@ -2,101 +2,101 @@
 #
 # Taskwarrior: Fake task/subtask "feature" via file directories and x rc files.
 
-add () {
-	init 1 &&
-	 {
-		 TASKSUBDIR=$tasksubdir task add "$@" ||
-			{
-				printf '%s\n' "error: add failed. see $tasksubdir" 1>&2;
-				return 1;
-			};
-		};
-};
+add() {
+    init 1 &&
+        {
+            TASKSUBDIR=$tasksubdir task add "$@" ||
+                {
+                    printf '%s\n' "error: add failed. see $tasksubdir" 1>&2
+                    return 1
+                }
+        }
+}
 
-_archive () {
-	test "$(
-		exec task rc.context:0 rc.hooks:0 rc.verbose:nothing \
-		 "(status:pending or status:recurring or status:waiting)" \
-		 count 2>/dev/null;
-	)" -eq 0 &&
-	 set -- * &&
-	 test "$#" -gt 0 -a "$1" != './*' &&
-	 command touch .archive &&
-	 cd .. &&
-	 command mv -- "$OLDPWD" "${OLDPWD%/*}/.${OLDPWD##*/}";
-};
+_archive() {
+    test "$(
+        exec task rc.context:0 rc.hooks:0 rc.verbose:nothing \
+            "(status:pending or status:recurring or status:waiting)" \
+            count 2>/dev/null
+    )" -eq 0 &&
+        set -- * &&
+        test "$#" -gt 0 -a "$1" != './*' &&
+        command touch .archive &&
+        cd .. &&
+        command mv -- "$OLDPWD" "${OLDPWD%/*}/.${OLDPWD##*/}"
+}
 
-archive () {
-	test "$TASKHOME" != "$PWD" &&
-	 _archive;
-};
+archive() {
+    test "$TASKHOME" != "$PWD" &&
+        _archive
+}
 
-archive_all () {
-	cd -- "$TASKHOME" ||
-	 return 1;
+archive_all() {
+    cd -- "$TASKHOME" ||
+        return 1
 
-	export LC_ALL=C;
+    export LC_ALL=C
 
-	exec find -H . \
-	 -mindepth 1 \
-	 -name '.*' -prune -o -type d -print |
-	exec sort -r |
-	while
-		read -r dir;
-	do
-		cd -- "$dir";
-		_archive;
-		cd -- "$TASKHOME";
-	done;
-};
+    exec find -H . \
+        -mindepth 1 \
+        -name '.*' -prune -o -type d -print |
+        exec sort -r |
+        while
+            read -r dir
+        do
+            cd -- "$dir"
+            _archive
+            cd -- "$TASKHOME"
+        done
+}
 
-goto () {
-	test "$TASKHOME" = "$PWD" ||
-	 {
-		 printf '%s\n' "error: cd into '$TASKHOME' first" 1>&2;
-		 return 1;
-	 };
+goto() {
+    test "$TASKHOME" = "$PWD" ||
+        {
+            printf '%s\n' "error: cd into '$TASKHOME' first" 1>&2
+            return 1
+        }
 
-	local d;
-	d=$(exec task _get "${1:?}.description");
+    local d
+    d=$(exec task _get "${1:?}.description")
 
-	test -n "$d" ||
-	 exit 1;
+    test -n "$d" ||
+        exit 1
 
-	exec find -H . -type d -name "$d" -o -name ".$d";
-};
+    exec find -H . -type d -name "$d" -o -name ".$d"
+}
 
-init () {
-	if
-		test -n "$1";
-	then
-		tasksubdir=$(command mktemp -d -p "$PWD");
-	else
-		command mkdir -p -- "${tasksubdir=$TASKHOME}";
-	fi;
+init() {
+    if
+        test -n "$1"
+    then
+        tasksubdir=$(command mktemp -d -p "$PWD")
+    else
+        command mkdir -p -- "${tasksubdir=$TASKHOME}"
+    fi
 
-	cd -- "$tasksubdir";
+    cd -- "$tasksubdir"
 
-	test -e ./.task -o -e ./.taskrc &&
-	 {
-		 printf '%s\n' "error: is already task repo" 1>&2;
-		 return 1;
-	 };
+    test -e ./.task -o -e ./.taskrc &&
+        {
+            printf '%s\n' "error: is already task repo" 1>&2
+            return 1
+        }
 
-	if
-		test "$PWD" != "$TASKHOME" -a -r ../.taskrc;
-	then
-		command cp ../.taskrc .taskrc;
-		command mkdir .task;
-		command cp -R ../.task/hooks .task/hooks;
-	else
-		command task config alias.d 'execute "task-dir"';
-		init_hooks;
-	fi;
-};
+    if
+        test "$PWD" != "$TASKHOME" -a -r ../.taskrc
+    then
+        command cp ../.taskrc .taskrc
+        command mkdir .task
+        command cp -R ../.task/hooks .task/hooks
+    else
+        command task config alias.d 'execute "task-dir"'
+        init_hooks
+    fi
+}
 
-init_hooks () {
-	command cat > .task/hooks/on-add-d630.sh <<'HOOK'
+init_hooks() {
+    command cat >.task/hooks/on-add-d630.sh <<'HOOK'
 #!/bin/sh
 #
 # s: Rename subtask directory.
@@ -159,94 +159,101 @@ exit 0;
 # vim: set ft=sh :
 HOOK
 
-	command chmod +x .task/hooks/on-add-d630.sh;
-};
+    command chmod +x .task/hooks/on-add-d630.sh
+}
 
-merge () {
-	test "$TASKHOME" = "$PWD" &&
-	 return 1;
+merge() {
+    test "$TASKHOME" = "$PWD" &&
+        return 1
 
-	export \
-	 TASKDATA=$TASKHOME/.task \
-	 TASKRC=$TASKHOME/.taskrc;
+    export \
+        TASKDATA=$TASKHOME/.task \
+        TASKRC=$TASKHOME/.taskrc
 
-	TASKRC=./.taskrc TASKDATA=./.task \
-	 task rc.hooks:0 rc.verbose:nothing rc.json.array:off export |
-	exec task rc.hooks:0 rc.verbose:nothing rc.json.array:off import 1>/dev/null;
+    TASKRC=./.taskrc TASKDATA=./.task \
+        task rc.hooks:0 rc.verbose:nothing rc.json.array:off export |
+        exec task rc.hooks:0 rc.verbose:nothing rc.json.array:off import 1>/dev/null
 
-	local c p u;
+    local c p u
 
-	c=${PWD##*/};
-	c=${c%%_*};
-	p=${PWD%/*};
-	p=${p##*/};
-	p=${p%%_*};
+    c=${PWD##*/}
+    c=${c%%_*}
+    p=${PWD%/*}
+    p=${p##*/}
+    p=${p%%_*}
 
-	u=$(exec task uuids "$c");
+    u=$(exec task uuids "$c")
 
-	exec task rc.hooks:0 rc.verbose:nothing \
-	 "uuid:$p" modify "dep:$u" 1>/dev/null;
-};
+    exec task rc.hooks:0 rc.verbose:nothing \
+        "uuid:$p" modify "dep:$u" 1>/dev/null
+}
 
-merge_all () {
-	cd -- "$TASKHOME" ||
-	 return 1;
+merge_all() {
+    cd -- "$TASKHOME" ||
+        return 1
 
-	# exec tree --charset unicode -din -f -I '.task' --prune --noreport . |
-	exec find -H . \
-	 -mindepth 1 \
-	 -name '.*' -prune -o -type d -print |
-	{
-		exec tee /dev/fd/8 |
-		exec xargs -I {} -P 8 -n 1 sh -c '
+    # exec tree --charset unicode -din -f -I '.task' --prune --noreport . |
+    exec find -H . \
+        -mindepth 1 \
+        -name '.*' -prune -o -type d -print |
+        {
+            exec tee /dev/fd/8 |
+                exec xargs -I {} -P 8 -n 1 sh -c '
 			cd -- "{}" &&
 			 exec task rc.hooks:0 rc.verbose:nothing rc.json.array:off export;
 		' |
-		exec task rc.hooks:0 rc.verbose:nothing rc.json.array:off import 1>/dev/null;
-	} 8>&1 |
-	exec awk -F / '
+                exec task rc.hooks:0 rc.verbose:nothing rc.json.array:off import 1>/dev/null
+        } 8>&1 |
+        exec awk -F / '
 		NF > 2 {
 			sub("_.*", "", $(NF - 1));
 			sub("_.*", "", $NF);
 			print $NF, $(NF - 1);
 		}
 	' |
-	exec xargs -I {} -n 1 -P 8 sh -c "
+        exec xargs -I {} -n 1 -P 8 sh -c "
 		exec task uuids {} |
 		exec sed 's#\([^ ]*\) \(.*\)#uuid:\1 modify dep:\2#'
 	" |
-	exec xargs -n 3 -P 8 task rc.hooks:0 rc.verbose:nothing 1>/dev/null;
-};
+        exec xargs -n 3 -P 8 task rc.hooks:0 rc.verbose:nothing 1>/dev/null
+}
 
-main () {
-	local cmd=${1:?};
-	shift 1;
+main() {
+    local cmd=${1:?}
+    shift 1
 
-	export \
-	 TASKDATA=./.task \
-	 TASKHOME=${TASKHOME:?} \
-	 TASKRC=./.taskrc;
+    export \
+        TASKDATA=./.task \
+        TASKHOME=${TASKHOME:?} \
+        TASKRC=./.taskrc
 
-	case $cmd in
-		(archiveall)
-			archive_all;;
-		(archive)
-			archive;;
-		(init)
-			init;;
-		(add)
-			add "$@";;
-		(merge)
-			merge;;
-		(mergeall)
-			merge_all;;
-		(goto)
-			goto "$1";;
-		(*)
-			printf '%s\n' "error: unknown command: $cmd" 1>&2;
-			return 1;
-	esac;
-};
+    case $cmd in
+        archiveall)
+            archive_all
+            ;;
+        archive)
+            archive
+            ;;
+        init)
+            init
+            ;;
+        add)
+            add "$@"
+            ;;
+        merge)
+            merge
+            ;;
+        mergeall)
+            merge_all
+            ;;
+        goto)
+            goto "$1"
+            ;;
+        *)
+            printf '%s\n' "error: unknown command: $cmd" 1>&2
+            return 1
+            ;;
+    esac
+}
 
-main "$@";
-
+main "$@"
diff --git a/mail-send b/mail-send
--- a/mail-send
+++ b/mail-send
@@ -2,43 +2,45 @@
 #
 # Sends mail via msmtp-queue and give notification + sound (via run-logger).
 
-exec 9<"$0";
-flock -n 9 || {
-	printf 'sorry, I am already running\n' 1>&2;
-	exit 1;
-};
+exec 9<"$0"
+if ! flock -n 9; then
+    printf 'sorry, I am already running\n' 1>&2
+    exit 1
+fi
 
-maildir=${XDG_VAR_HOME:?}/mail/queue;
-[[ -d $maildir ]] || {
-	printf "maildir '%s' is not a directory\n" "$maildir" 1>&2;
-	exit 1;
-};
+maildir=${XDG_VAR_HOME:?}/mail/queue
+if ! [[ -d $maildir ]]; then
+    printf "maildir '%s' is not a directory\n" "$maildir" 1>&2
+    exit 1
+fi
 
-shopt -s nullglob;
-shopt -s extglob;
-shopt -s dotglob;
-set -- "$maildir/"!(\.*);
+shopt -s nullglob
+shopt -s extglob
+shopt -s dotglob
+set -- "$maildir/"!(\.*)
 
-(($#)) &&
-	cnt=$# ||
-		exit 1;
+if (($#)); then
+    cnt=$#
+else
+    exit 1
+fi
 
-i=0;
-until
-	! (($#));
-do
-	case $i in
-		(30)
-			run-logger 3 .email.error "Delivery error. [posteo] Mails not sent: $cnt";
-			exit 1;;
-		(*)
-			msmtpqw -r;
-			set -- "$maildir/"!(\.*);
-			((i++));
-			sleep 1;
-	esac;
-done;
+i=0
+until ! (($#)); do
+    case $i in
+        30)
+            command -- run-logger 3 .email.error "Delivery error. [posteo] Mails not sent: $cnt"
+            exit 1
+            ;;
+        *)
+            command -- msmtpqw -r
+            set -- "$maildir/"!(\.*)
+            ((i++))
+            command -- sleep 1
+            ;;
+    esac
+done
 
-run-logger 6 .email.bounced "[posteo] Sent Mails: $cnt";
+command -- run-logger 6 .email.bounced "[posteo] Sent Mails: $cnt"
 
-# vim: set ft=sh :
+# vim: set ft=zsh :
diff --git a/open b/open
--- a/open
+++ b/open
@@ -5,57 +5,60 @@
 # TODO(D630): complete the "string" part.
 
 flag_A= \
-flag_f= \
-g= \
-m= \
-mime= \
-opt=;
+    flag_f= \
+    g= \
+    m= \
+    mime= \
+    opt=
 
-while
-	getopts :A:f: opt;
-do
-	case $opt in
-		(A)
-			case $OPTARG in
-				(view|vview|edit|vedit|compose|vcompose|dog|cdog|about|gview|gedit|gcompose)
-					flag_A=${flag_A:+$flag_A }$OPTARG;;
-				(*)
-					printf 'Unknown action: %s\n' "$OPTARG" 1>&2;
-					exit 1;;
-			esac;;
-		(f)
-			readonly flag_f=$OPTARG;;
-		(\?)
-			printf 'Unknown flag: -%s\n' "$OPTARG" 1>&2;
-			exit 1;;
-	esac;
-done;
+while getopts :A:f: opt; do
+    case $opt in
+        A)
+            case $OPTARG in
+                view | vview | edit | vedit | compose | vcompose | dog | cdog | about | gview | gedit | gcompose)
+                    flag_A=${flag_A:+$flag_A }$OPTARG
+                    ;;
+                *)
+                    printf 'Unknown action: %s\n' "$OPTARG" 1>&2
+                    exit 1
+                    ;;
+            esac
+            ;;
+        f)
+            readonly flag_f=$OPTARG
+            ;;
+        \?)
+            printf 'Unknown flag: -%s\n' "$OPTARG" 1>&2
+            exit 1
+            ;;
+    esac
+done
 
-test -n "$flag_f" || {
-	printf 'File operand is missing\n' 1>&2;
-	exit 1;
-};
+if test -z "$flag_f"; then
+    printf 'File operand is missing\n' 1>&2
+    exit 1
+fi
 
-eval "$(mime_database detect "$flag_f")";
+eval "$(exec mime_database detect "$flag_f")"
 
-if
-	test "$m" != ?;
-then
-	mime=$m;
-elif
-	test "$g" != ?;
-then
-	mime=$g;
+if test "$m" != ?; then
+    mime=$m
+elif test "$g" != ?; then
+    mime=$g
 else
-	mime=$(file -L -b --mime-type "$flag_f");
-fi;
+    mime=$(exec file -L -b --mime-type "$flag_f")
+fi
 
-. "$XDG_CONFIG_HOME/"mailcap.d/$mime;
+. "${XDG_CONFIG_HOME:?}/mailcap.d/$mime"
 
-for A in $flag_A; do
-	"$A" "$flag_f" &&
-		break;
-	printf 'action for mime <%s> was <%s>\n' "$mime" "$A" 1>&2;
-done;
+set -f
+IFS=' '
+set -- $flag_A
+
+for A in "$@"; do
+    "$A" "$flag_f" &&
+        break
+    printf 'action for mime <%s> was <%s>\n' "$mime" "$A" 1>&2
+done
 
 # vim: set ft=sh :
diff --git a/rest b/rest
--- a/rest
+++ b/rest
@@ -3,19 +3,20 @@
 # Wrapper: Use several REST APIs.
 
 case $1 in
-	(bitbucket|confluence|jira|rocketchat)
-		export API=$1-rest-api;
-		if test "${2:?error: operation missing}" = libexec;
-		then
-			shift 2;
-			exec "$API-libexec" "$@";
-		else
-			shift 1;
-			exec "$API" "$@";
-		fi;;
-	(*)
-		printf 'error: unknown service %s\n' "$1";
-		exit 1;;
-esac;
+    bitbucket | confluence | jira | rocketchat)
+        export API=$1-rest-api
+        if test "${2:?error: operation missing}" = libexec; then
+            shift 2
+            exec "$API-libexec" "$@"
+        else
+            shift 1
+            exec "$API" "$@"
+        fi
+        ;;
+    *)
+        printf 'error: unknown service %s\n' "$1" >&2
+        exit 1
+        ;;
+esac
 
 # vim: set ft=sh noexpandtab :
diff --git a/rest-api b/rest-api
--- a/rest-api
+++ b/rest-api
@@ -3,43 +3,45 @@
 # Default REST API functions.
 
 curl() {
-	exec curl -v -s -n \
-		-X "$(echo "$method" | exec tr '[:lower:]' '[:upper:]')" \
-		"${server_address:-.}$endpoint" \
-		${1:+"$@"};
+    exec curl -v -s -n \
+        -X "$(echo "$method" | exec tr '[:lower:]' '[:upper:]')" \
+        "${server_address:-.}$endpoint" \
+        ${1:+"$@"}
 }
 
 delete() {
-	\curl;
+    \curl
 }
 
 get() {
-	\curl;
+    \curl
 }
 
 post() {
-	\curl -H 'Content-Type: application/json' ${1:+-d "$1"};
+    \curl -H 'Content-Type: application/json' ${1:+-d "$1"}
 }
 
 main() {
-	local \
-		endpoint \
-		method;
+    local \
+        endpoint \
+        method
 
-	eval "
-		case \$1 in
-			(${method_casematch:-delete|get|post})
-				method=\$1;
-				endpoint=\${2:?'error: endpoint missing'};;
-			(*)
-				echo 'error: valid method missing' 1>&2;
-				return 1;
-		esac
-	";
+    eval "
+        case \$1 in
+            (${method_casematch:-delete|get|post})
+                method=\$1
+                endpoint=\${2:?'error: endpoint missing'}
+                ;;
+            (*)
+                echo 'error: valid method missing' 1>&2
+                return 1
+                ;;
+        esac
+    "
 
-	shift 2;
+    shift 2
 
-	"$method" "$@";
-};
+    "$method" "$@"
+}
 
-# vim: set ft=sh noexpandtab :
+# vim: set ft=sh :
diff --git a/rocketchat-rest-api-libexec b/rocketchat-rest-api-libexec
--- a/rocketchat-rest-api-libexec
+++ b/rocketchat-rest-api-libexec
@@ -2,53 +2,53 @@
 #
 # Libexec: Rocketchat REST API.
 
-export API=${API:-${api:-rocketchat-rest-api}};
+export API=${API:-${api:-rocketchat-rest-api}}
 
 f_login() {
-    local pw;
-    read -e -s -r -p 'pw: ' pw;
+    local pw
+    IFS= read -e -s -r -p 'pw: ' pw
 
     local \
         auth_token_file=$HOME/.rocketchat_wir_invalid_auth_token \
-        user=${1:-"error: user missing"};
+        user=${1:-'error: user missing'}
 
-    > "$auth_token_file";
-    command chmod 640 "$auth_token_file";
+    >"$auth_token_file"
+    command -- chmod 640 "$auth_token_file"
 
     local auth_token=$(
         ROCKETCHAT_REST_TOKEN=. \
-        ROCKETCHAT_REST_USER_ID=. \
-        exec "$API" post login \
-            '{"user": "'"$user"'", "password": "'"${pw:?error: pw missing}"'"}' |
-        exec jq -r .data.authToken;
-    );
+            ROCKETCHAT_REST_USER_ID=. \
+            exec -- "$API" post login \
+                '{"user": "'"$user"'", "password": "'"${pw:?error: pw missing}"'"}' |
+            exec -- jq -r .data.authToken
+    )
 
-    [[ -n "$auth_token" && "$auth_token" != null ]] || {
-        echo 'login failed' 1>&2;
-        exit 1;
-    }
+    if [[ -z "$auth_token" || "$auth_token" == null ]]; then
+        echo 'login failed' 1>&2
+        exit 1
+    fi
 
-    printf '%s\n' "$auth_token" >> "$auth_token_file";
-    printf '%s\n' "$auth_token";
+    printf '%s\n' "$auth_token" >>"$auth_token_file"
+    printf '%s\n' "$auth_token"
 }
 
 f_logout() (
-    local ROCKETCHAT_REST_USER_ID=${1:-"error: user id missing"};
+    local ROCKETCHAT_REST_USER_ID=${1:-'error: user id missing'}
 
-    local auth_token_file=$HOME/.rocketchat_wir_invalid_auth_token;
+    local auth_token_file=$HOME/.rocketchat_wir_invalid_auth_token
     local ROCKETCHAT_REST_TOKEN=$(<"$auth_token_file") ||
-        exit 1;
+        exit 1
 
     export \
         ROCKETCHAT_REST_TOKEN \
-        ROCKETCHAT_REST_USER_ID;
+        ROCKETCHAT_REST_USER_ID
 
-    exec "$API" post logout |
-    exec jq -r .;
+    exec -- "$API" post logout |
+        command -- jq -r .
 
-    exec rm "$auth_token_file";
+    exec -- rm -- "$auth_token_file"
 )
 
-${1:+"f_$@"};
+${1:+"f_$@"}
 
-# vim: set ft=sh :
+# vim: set ft=zsh :
diff --git a/run b/run
--- a/run
+++ b/run
@@ -7,97 +7,108 @@
 # -N open cmd in new terminal-emulator
 
 typeset \
-	cmd \
-	opt;
+    cmd \
+    opt
 
 typeset -i \
-	OLDOPTIND=1 \
-	OPTERR=0 \
-	OPTIND=1 \
-	flag_F=0 \
-	flag_K=0 \
-	flag_N=0;
+    OLDOPTIND=1 \
+    OPTERR=0 \
+    OPTIND=1 \
+    flag_F=0 \
+    flag_K=0 \
+    flag_N=0
 
-while
-	getopts :FKN opt
-do
-	case $opt in
-		(F)
-			flag_F=1;;
-		(K)
-			flag_K=1;;
-		(N)
-			flag_N=1;;
-		(\?)
-			printf "error: unknown flag: '%s'\n" "$OPTARG" 1>&2;
-			exit 1;;
-	esac;
+while getopts :FKN opt; do
+    case $opt in
+        F)
+            flag_F=1
+            ;;
+        K)
+            flag_K=1
+            ;;
+        N)
+            flag_N=1
+            ;;
+        \?)
+            printf "error: unknown flag: '%s'\n" "$OPTARG" 1>&2
+            exit 1
+            ;;
+    esac
 
-	((OLDOPTIND != OPTIND)) &&
-		if
-			[[ -n $2 && $2 == -- ]]
-		then
-			shift 2;
-			break;
-		else
-			OPTIND=1;
-			shift 1;
-		fi;
+    if ((OLDOPTIND != OPTIND)); then
+        if [[ -n $2 && $2 == -- ]]; then
+            shift 2
+            break
+        else
+            OPTIND=1
+            shift 1
+        fi
+    fi
 
-	OLDOPTIND=$OPTIND;
-done;
+    OLDOPTIND=$OPTIND
+done
 
-(($#)) || {
-	printf 'error: command missing\n' 1>&2;
-	exit 1;
-};
+if ! (($#)); then
+    printf 'error: command missing\n' 1>&2
+    exit 1
+fi
 
-if
-	command -v "$1" 1>/dev/null 2>&1;
-then
-	cmd=$1;
-	shift 1;
+if command -v "$1" 1>/dev/null 2>&1; then
+    cmd=$1
+    shift 1
 else
-	printf "error: command not found: '%s'\n" "$1" 1>&2;
-	exit 1;
-fi;
+    printf "error: command not found: '%s'\n" "$1" 1>&2
+    exit 1
+fi
 
-if
-	test-ctty;
-then
-	case $flag_F$flag_N$flag_K in
-		(111)
-			exec daemonize x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q};exec ${SHELL:-sh}";;
-		(110)
-			exec daemonize x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q}";;
-		(100)
-			exec daemonize -f "$cmd" "$@";;
-		(011)
-			exec x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q};exec ${SHELL:-sh}";;
-		(010)
-			exec x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q}";;
-		(001)
-			exec ${SHELL:-sh} -c "$cmd ${*@Q};printf 'Press ENTER to continue\n';read";;
-		(000)
-			exec "$cmd" "$@";;
-	esac;
+if command -- test-ctty; then
+    case $flag_F$flag_N$flag_K in
+        111)
+            exec -- daemonize x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q};exec ${SHELL:-sh}"
+            ;;
+        110)
+            exec -- daemonize x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q}"
+            ;;
+        100)
+            exec -- daemonize -f "$cmd" "$@"
+            ;;
+        011)
+            exec -- x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q};exec ${SHELL:-sh}"
+            ;;
+        010)
+            exec -- x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q}"
+            ;;
+        001)
+            exec -- ${SHELL:-sh} -c "$cmd ${*@Q};printf 'Press ENTER to continue\n';read"
+            ;;
+        000)
+            exec -- "$cmd" "$@"
+            ;;
+    esac
 else
-	case $flag_F$flag_N$flag_K in
-		(111)
-			exec daemonize x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q};exec ${SHELL:-sh}";;
-		(110)
-			exec daemonize x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q}";;
-		(100)
-			exec daemonize "$cmd" "$@";;
-		(011)
-			exec x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q};exec ${SHELL:-sh}";;
-		(010)
-			exec x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q}";;
-		(001)
-			exec ${SHELL:-sh} -c "$cmd ${*@Q};printf 'Press ENTER to continue\n';read";;
-		(000)
-			exec "$cmd" "$@";;
-	esac;
-fi;
+    case $flag_F$flag_N$flag_K in
+        111)
+            exec -- daemonize x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q};exec ${SHELL:-sh}"
+            ;;
+        110)
+            exec -- daemonize x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q}"
+            ;;
+        100)
+            exec -- daemonize "$cmd" "$@"
+            ;;
+        011)
+            exec -- x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q};exec ${SHELL:-sh}"
+            ;;
+        010)
+            exec -- x-terminal -e "${SHELL:-sh}" -c "$cmd ${*@Q}"
+            ;;
+        001)
+            exec -- ${SHELL:-sh} -c "$cmd ${*@Q};printf 'Press ENTER to continue\n';read"
+            ;;
+        000)
+            exec -- "$cmd" "$@"
+            ;;
+    esac
+fi
 
-# vim: set ft=sh :
+# vim: set ft=zsh :
diff --git a/task-local b/task-local
--- a/task-local
+++ b/task-local
@@ -2,26 +2,27 @@
 #
 # Simple wrapper for using taskwarrior with local "task-repos".
 
-export TASKRC=${TASKRC:-$PWD/.task/taskrc};
+export TASKRC=${TASKRC:-$PWD/.task/taskrc}
 
 case $1 in
-	(init)
-		if
-			test -d "$PWD/.task";
-		then
-			printf '%s:Error:82: Could not create a task repository: "%s/.task/" already exists\n' \
-				"$0" "$PWD" 1>&2;
-			exit 82;
-		else
-			mkdir -p -- "$PWD/.task/data" &&
-				task config data.location "$PWD/.task/data";
-		fi;;
-	(--)
-		shift 1;
-		task "$@";;
-	(*)
-		printf '%s:Error:83: Unknown parameter: %s\n' "$0" "$1" 1>&2;
-		exit 83;;
-esac;
+    init)
+        if test -d "$PWD/.task"; then
+            printf '%s:Error:82: Could not create a task repository: "%s/.task/" already exists\n' \
+                "$0" "$PWD" 1>&2
+            exit 82
+        else
+            command -- mkdir -p -- "$PWD/.task/data" &&
+                exec task config data.location "$PWD/.task/data"
+        fi
+        ;;
+    --)
+        shift 1
+        exec task "$@"
+        ;;
+    *)
+        printf '%s:Error:83: Unknown parameter: %s\n' "$0" "$1" 1>&2
+        exit 83
+        ;;
+esac
 
 # vim: set ft=sh :
